### ISSUE TITLE
Different answer for pooled variance from sample.decopm() function with pooled variance formula

### ISSUE THREAD

**Issue by lida-R** [ben-oneill/utilities#9]
Hello,

Thank you for your nice package and functions. 
I am estimating the Pooled variance for couple of groups with different sample size. I applied both, following formula and sample.decomp() function but I got different answers. May I know which formula you used for building up the pooled calculation of sample.decopm() function?
The formula I applied:

![image](https://user-images.githubusercontent.com/9890844/146463636-f3ccab60-695d-4422-9cf8-81a5d4fb3ba6.png)

Thank you for your help in advance,
Lida

**Comment by ben-oneill** [comment]
Hi Lida,

I'm glad you like the package.  (Please feel free to give it a star if you like it!)

The sample decomposition results are written up in a paper I have put on ARXIV<https://arxiv.org/abs/2109.05801>.  You might also be interested in a related paper here<https://www.researchgate.net/publication/269286078_Some_Useful_Moment_Results_in_Sampling_Problems> that looks at the sample variance decomposition and other moment results.  As you will see from both papers, the pooled sample variance is not fully determined by the sample variances of the parts --- it also depends on their sample means (so the formula is actually more complicated than the one you have given).

Let me know if you have any further difficulties understanding the method.

Thanks,
Ben.

________________________________
From: lida-R ***@***.***>
Sent: Friday, 17 December 2021 10:27 AM
To: ben-oneill/utilities ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ben-oneill/utilities] Different answer for pooled variance from sample.decopm() function with pooled variance formula (Issue #9)


Hello,

Thank you for your nice package and functions.
I am estimating the Pooled variance for couple of groups with different sample size. I applied both, following formula and sample.decomp() function but I got different answers. May I know which formula you used for building up the pooled calculation of sample.decopm() function?
The formula I applied:

[image]<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F9890844%2F146463636-f3ccab60-695d-4422-9cf8-81a5d4fb3ba6.png&data=04%7C01%7C%7C72dc3cb4b5834caa570108d9c0ebaa89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752940684193853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=e%2Bynctrwh%2Bs3Q8GwlsTlfRO%2F7osKJoixiy5ECKQmt0U%3D&reserved=0>

Thank you for your help in advance,
Lida

—
Reply to this email directly, view it on GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fben-oneill%2Futilities%2Fissues%2F9&data=04%7C01%7C%7C72dc3cb4b5834caa570108d9c0ebaa89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752940684193853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=BFubLfYSYUGPoI%2Fhhvao1X1pa2qYPbfULzW42jB5IaQ%3D&reserved=0>, or unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALMWGCXJI2ZVORQRRSQFW7LURJYXDANCNFSM5KHQ457A&data=04%7C01%7C%7C72dc3cb4b5834caa570108d9c0ebaa89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752940684193853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fg1ZGfkRZhNWZXSAayB47is0ymZDOIbW%2BsoMdmqCgY0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C72dc3cb4b5834caa570108d9c0ebaa89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752940684193853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ibIyzTyk9D2jF5tBwvy%2F0GpTWaO8cjIZOLs0udjoIDI%3D&reserved=0> or Android<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C72dc3cb4b5834caa570108d9c0ebaa89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637752940684193853%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=m3aQ0KoZ3FFSdORjkI%2FX%2B4epkyKL3%2FkursYNqynbq9U%3D&reserved=0>.

**Comment by ben-oneill** [comment]
Sorry --- Lida.  (Mis-typed!)

________________________________

**Comment by lida-R** [comment]
Thank you Ben for your reply. 
So, As far as I understood, the pooled variance is calculated by your package is kind of similar to the total variation (Within + Between groups) in ANOVA and considers both variation not only within groups variation (Pooled variance or Sum of Square Error in ANOVA). Am I right?

**Comment by ben-oneill** [comment]
Yes, that is correct --- the variance decomposition uses an underlying decomposition for the sum-of-squares, so they are essentially the same kind of calculation.

________________________________
